### ISSUE TITLE
First README example may have incorrect import

### ISSUE THREAD

**Issue by MattDavis00** [MattDavis00/lottie-svelte#15]
It may have the incorrect import statement to the `Lottie` component. Needs investigation. Making this issue so I don't forget

**Comment by MattDavis00** [comment]
Don't think Lottie is a default index.ts export anymore. May need adding back

**Comment by MarilorV** [comment]
Hello! Thank you for this package. In my js project, import worked with
` import { Lottie } from "lottie-svelte";`

**Comment by MattDavis00** [comment]
> Hello! Thank you for this package. In my js project, import worked with
> ` import { Lottie } from "lottie-svelte";`

Thank you for the confirmation. I thought this may be the case. Hope the package is working well for you otherwise. To fix this I will either update the documentation to match, or re-export the Lottie component as the default "lottie-svelte" index.ts export; probably the former.
