### ISSUE TITLE
Add `class` and `style` props

### ISSUE THREAD

**Issue by cuire** [MattDavis00/lottie-svelte#20]
This feature slightly reduces the boilerplate.

From this:
```svelte
<div class="mb-5 h-60">
	<Lottie path={path} loop={false} />
</div>
```

To this:
```svelte
<Lottie class="mb-5 h-60" path={path} loop={false} />
```

**Comment by MattDavis00** [comment]
Fixed as of `1.3.5`. Any property that is not defined/used by lottie-svelte is now automatically passed to the container. Therefore `class` and `style`, as well as others, can now be applied to the child container constructed within Lottie.
