### ISSUE TITLE
The `destroy` method is not being called

### ISSUE THREAD

**Issue by rbozan** [MattDavis00/lottie-svelte#21]
I have a feeling this library slows down my application after showing a lot of animations. Now I am seeing that the lottie-web library has a `destroy` method: https://github.com/airbnb/lottie-web#destroy but I don't see this method being called here on destroy of the component. I am not sure if that is needed?

Simply adding

```ts
    	return () => {
	 		animation.destroy()
		}
```

to the onMount function would fix it.

See: https://github.com/MattDavis00/lottie-svelte/pull/22

**Comment by MattDavis00** [comment]
Fixed and merged in https://github.com/MattDavis00/lottie-svelte/pull/22

**Comment by MattDavis00** [comment]
Fix is included in the lastest release:
https://github.com/MattDavis00/lottie-svelte/releases/tag/v1.3.7
https://www.npmjs.com/package/lottie-svelte/v/1.3.7
